name: Simulate DDoS Attack

on:
  push:
    branches:
      - master

jobs:
  attack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install HTTP tool (httpie)
      run: |
        sudo apt-get update
        sudo apt-get install -y httpie

    - name: Simulate DDoS attack
      run: |
        for i in {1..1000}; do
          http --ignore-stdin https://63ca-197-240-82-54.ngrok-free.app &  # Replace with your Ngrok URL
        done

    - name: Wait for attack to finish
      run: sleep 10
